// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguiNutri.App.Persistencia;

namespace SeguiNutri.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211005183056_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SeguiNutri.App.Dominio.HistoricoBasico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HistoricoBasicos");
                });

            modelBuilder.Entity("SeguiNutri.App.Dominio.HistoricoDatos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("HistoricoBasicoPacienteId")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdRegistro")
                        .HasColumnType("int");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("int");

                    b.Property<int?>("SeguimientoNutricionalPacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HistoricoBasicoPacienteId");

                    b.HasIndex("RegistroId");

                    b.HasIndex("SeguimientoNutricionalPacienteId");

                    b.ToTable("HistoricosDatos");
                });

            modelBuilder.Entity("SeguiNutri.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("SeguiNutri.App.Dominio.RegistroDatos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("CaloriasConsumi")
                        .HasColumnType("float");

                    b.Property<double>("CarbohidratosConsumi")
                        .HasColumnType("float");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<double>("GrasaConsumi")
                        .HasColumnType("float");

                    b.Property<int>("Id_Paciente")
                        .HasColumnType("int");

                    b.Property<double>("MedidasAntropometricas")
                        .HasColumnType("float");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<double>("ProteinaConsumi")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("RegistrosDatos");
                });

            modelBuilder.Entity("SeguiNutri.App.Dominio.SeguimientoNutris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("HistoricoBasicoPacienteId")
                        .HasColumnType("int");

                    b.Property<int>("IdCoach")
                        .HasColumnType("int");

                    b.Property<int>("IdNutricionista")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("SugerenciasCuid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HistoricoBasicoPacienteId");

                    b.ToTable("SeguimientosNutri");
                });

            modelBuilder.Entity("SeguiNutri.App.Dominio.Coach", b =>
                {
                    b.HasBaseType("SeguiNutri.App.Dominio.Persona");

                    b.HasDiscriminator().HasValue("Coach");
                });

            modelBuilder.Entity("SeguiNutri.App.Dominio.Nutricionista", b =>
                {
                    b.HasBaseType("SeguiNutri.App.Dominio.Persona");

                    b.Property<int>("IdNutricionista")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Nutricionista");
                });

            modelBuilder.Entity("SeguiNutri.App.Dominio.Paciente", b =>
                {
                    b.HasBaseType("SeguiNutri.App.Dominio.Persona");

                    b.Property<int?>("CoachAsignadoPacienteId")
                        .HasColumnType("int");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HistoricoBasicoPacienteId")
                        .HasColumnType("int");

                    b.Property<int?>("HistoricoDatosPacienteId")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("NutricionistaAsignadoPacienteId")
                        .HasColumnType("int");

                    b.Property<int?>("RegistroDatosPacienteId")
                        .HasColumnType("int");

                    b.Property<int?>("SeguimientoNutrisPacienteId")
                        .HasColumnType("int");

                    b.HasIndex("CoachAsignadoPacienteId");

                    b.HasIndex("HistoricoBasicoPacienteId");

                    b.HasIndex("HistoricoDatosPacienteId");

                    b.HasIndex("NutricionistaAsignadoPacienteId");

                    b.HasIndex("RegistroDatosPacienteId");

                    b.HasIndex("SeguimientoNutrisPacienteId");

                    b.HasDiscriminator().HasValue("Paciente");
                });

            modelBuilder.Entity("SeguiNutri.App.Dominio.HistoricoDatos", b =>
                {
                    b.HasOne("SeguiNutri.App.Dominio.HistoricoBasico", "HistoricoBasicoPaciente")
                        .WithMany()
                        .HasForeignKey("HistoricoBasicoPacienteId");

                    b.HasOne("SeguiNutri.App.Dominio.RegistroDatos", "Registro")
                        .WithMany()
                        .HasForeignKey("RegistroId");

                    b.HasOne("SeguiNutri.App.Dominio.SeguimientoNutris", "SeguimientoNutricionalPaciente")
                        .WithMany()
                        .HasForeignKey("SeguimientoNutricionalPacienteId");

                    b.Navigation("HistoricoBasicoPaciente");

                    b.Navigation("Registro");

                    b.Navigation("SeguimientoNutricionalPaciente");
                });

            modelBuilder.Entity("SeguiNutri.App.Dominio.SeguimientoNutris", b =>
                {
                    b.HasOne("SeguiNutri.App.Dominio.HistoricoBasico", "HistoricoBasicoPaciente")
                        .WithMany()
                        .HasForeignKey("HistoricoBasicoPacienteId");

                    b.Navigation("HistoricoBasicoPaciente");
                });

            modelBuilder.Entity("SeguiNutri.App.Dominio.Paciente", b =>
                {
                    b.HasOne("SeguiNutri.App.Dominio.Coach", "CoachAsignadoPaciente")
                        .WithMany()
                        .HasForeignKey("CoachAsignadoPacienteId");

                    b.HasOne("SeguiNutri.App.Dominio.HistoricoBasico", "HistoricoBasicoPaciente")
                        .WithMany()
                        .HasForeignKey("HistoricoBasicoPacienteId");

                    b.HasOne("SeguiNutri.App.Dominio.HistoricoDatos", "HistoricoDatosPaciente")
                        .WithMany()
                        .HasForeignKey("HistoricoDatosPacienteId");

                    b.HasOne("SeguiNutri.App.Dominio.Nutricionista", "NutricionistaAsignadoPaciente")
                        .WithMany()
                        .HasForeignKey("NutricionistaAsignadoPacienteId");

                    b.HasOne("SeguiNutri.App.Dominio.RegistroDatos", "RegistroDatosPaciente")
                        .WithMany()
                        .HasForeignKey("RegistroDatosPacienteId");

                    b.HasOne("SeguiNutri.App.Dominio.SeguimientoNutris", "SeguimientoNutrisPaciente")
                        .WithMany()
                        .HasForeignKey("SeguimientoNutrisPacienteId");

                    b.Navigation("CoachAsignadoPaciente");

                    b.Navigation("HistoricoBasicoPaciente");

                    b.Navigation("HistoricoDatosPaciente");

                    b.Navigation("NutricionistaAsignadoPaciente");

                    b.Navigation("RegistroDatosPaciente");

                    b.Navigation("SeguimientoNutrisPaciente");
                });
#pragma warning restore 612, 618
        }
    }
}
